services:
  bot:
    image: ghcr.io/whileshesuckmyblood/tg-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    pull_policy: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - bot
