name: CI/CD для TG бота

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Установка зависимостей
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Запуск тестов
        run: pytest test.py

      - name: Сборка Docker образа
        run: docker build -t tg-bot:${{ github.sha }} .

      - name: Логинимся в GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: whileshesuckmyblood
          password: ${{ secrets.GHCR_PAT }}

      - name: Пуш Docker образа в GHCR
        run: |
          docker tag tg-bot:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/tg-bot:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/tg-bot:${{ github.sha }}

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Деплой на VPS через SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_TAG
          script: |
            cd ~/tgbotproject/test
            
            echo "login"
            export IMAGE_TAG=${{ github.sha }}
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u whileshesuckmyblood --password-stdin
            
            echo "pull"
            docker pull ghcr.io/whileshesuckmyblood/tg-bot:$IMAGE_TAG
          
            echo "deploy"
            export IMAGE_TAG=$IMAGE_TAG
            docker compose up -d --force-recreate --remove-orphans
          
            echo "деплой завершён $(date)"
